### PR TITLE
Create adithya.md

### PR DESCRIPTION
**Pull request by adithya-r-prabhu**

### CODE REVIEW

**Comment by CSYClubIIITK** [comment]
Hey glad to see you being active in the Open Source,
Please kindly follow the conditions and format specified in the readme file.

**Comment by adithya-r-prabhu** [comment]
Hey, corrections made.
kindly check.

**Comment by CSYClubIIITK** [comment]
Exciting!!!
Format Check ✅
Oh wait!!!
Did you join our Discord Server, 
And Make sure You have registered in Hacktoberfest as the 1st thing.
https://hacktoberfest.com/
Register Here, after registration only ur contributions get counted..
If everything is done let me know will merge your PR

**Comment by adithya-r-prabhu** [comment]
Discord Joined ✅
Registration ✅

**Comment by adithya-r-prabhu** [comment]
Please merge the PR

**Pull request merged**
